### ISSUE TITLE
User reports Contact page not working

### ISSUE THREAD

**Issue by jorvis** [nemoarchive/analytics#121]
From a user:

```
I tried to submit a question via the web interface but the form appears to not work, the error I got from this page https://nemoanalytics.org/contact.html was :Oops. Something went wrong. Please try again, but if this continues please contact jorvis@gmail.com for help.

(Error: 500 Internal Server Error) 
```

**Comment by adkinsrs** [comment]
apparently the "python-dotenv" module is not installed on the nemo-prod-202006 server and the gear-prod-20200713 which I have taken care of.

Secondly the /var/www/.env file is on neither the nemo-prod-202006 nor the gear-prod-20200713 servers (it existed on the previous gear-production server).  This file holds the github authentication credentials so that the Contact page can auto-create a github issue. See Issue #626 for reference.

**Comment by jorvis** [comment]
I can fix these issues then or are you already working on it?

**Comment by adkinsrs** [comment]
I installed the python-dotenv file to the servers.  All that remains is the scp the .env file from the previous gear-production server to the current servers, and you can take care of it if you want.  I did not commit that file to the git repo because that seemed like a security thing I would want to avoid.

**Comment by jorvis** [comment]
Quite correct.  I'll take care of it.

**Comment by jorvis** [comment]
I have placed the .env file on gear-production, gear-devel, and nemo-production.
