### ISSUE TITLE
custom X and Y axis limits on scatter plots

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#133]
currently the view curator rounds the axes limits to whole units. this is fine most of the time, except when the axis spans a small number of units, which results in a lot of empty space in the plot. 

can we provide the option for the user to set precise custom X and Y axis limits?

this is not only useful for manicuring individual plots, but can also be very useful in coordinating axes across multiple related dataset views.

**Comment by adkinsrs** [comment]
Should be doable.  Currently the plotting internals will do some calculations which include taking the floor of the min value of the data and the ceiling of the max value of the data, which are used to calculate the range of the axes and the number of ticks.  It seems that if you provide the number of ticks you want to the functions, these calculations are ignored, and the min/max values are not rounded off.

So I think I can add the following for each axis... min/max tick value and number of ticks.  Or as an alternative, I can just add an option for the number of ticks and it'll determine the range automatically.

**Comment by adkinsrs** [comment]
I am making progress on the implementation of this.  Still need to add validation checks that both numbers in the axis limits are provided (since Plotly requires a min and a max value)

**plot without y-axis range (x-axis is categorical so no range)**
<img width="1440" alt="Screen Shot 2020-08-27 at 4 47 47 PM" src="https://user-images.githubusercontent.com/5665914/91493417-48544c80-e885-11ea-8874-53c8534c0f4c.png">

**same plot with y-axis range**
<img width="1440" alt="Screen Shot 2020-08-27 at 4 48 11 PM" src="https://user-images.githubusercontent.com/5665914/91493427-4c806a00-e885-11ea-9e4d-b49aea354662.png">
